# Change these first
owner: mission-apprentissage # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Catalogue
    url: https://catalogue.apprentissage.beta.gouv.fr/
  - name: Catalogue API
    url: https://catalogue.apprentissage.beta.gouv.fr/api
  - name: Catalogue Recette
    url: https://catalogue-recette.apprentissage.beta.gouv.fr/
  - name: Catalogue API Recette
    url: https://catalogue-recette.apprentissage.beta.gouv.fr/api
  - name: API Tables de correspondances
    url: https://tables-correspondances.apprentissage.beta.gouv.fr/api
  - name: API Tables de correspondances recette
    url: https://tables-correspondances-recette.apprentissage.beta.gouv.fr/api

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: /upptime
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Mission-apprentissage Uptime
  introTitle: "**Mission apprentissage** statuts des services"
  introMessage: Cette page de status vous donne des informations en temps-réel du niveau de disponibilité de nos services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/2 * * * *"
